default_context:
    full_name: KimLab
    email: alex.strokach@utoronto.ca
    git_url: https://gitlab.com
    git_username: kimlab
    anaconda_username: kimlab
    pypi_username: kimlab
    project_name: kmbio
    project_slug: kmbio
    project_import: kmbio
    project_short_description: Fork of `biopython.PDB` with special powers.
    docs_secret_key: ""
    version: "2.0.18"
    create_author_file: "y"
    open_source_license: MIT License
    _copy_without_render:
        - docs/output_toggle.tpl
        - docs/_templates/logo-image.html
