image: condaforge/linux-anvil:latest

stages:
  - build
  - test
  - deploy

cache:
  paths:
    - conda-cache

# === Variables ===

variables:
  PACKAGE_VERSION: 2.0.5

.py35: &py35
  PYTHON_VERSION: "3.5"

.py36: &py36
  PYTHON_VERSION: "3.6"

# === Configurations ===

.conda_configure: &conda_configure
  before_script:
    # Make conda cache and bld folders
    - mkdir -p "${CI_PROJECT_DIR}/conda-bld" "${CI_PROJECT_DIR}/conda-cache"
    # Conda configure
    - conda config --set channel_priority true
    - conda config --append channels conda-forge
    - conda config --append channels ostrokach-forge
    - conda config --append channels bioconda
    - case "${PACKAGE_VERSION}" in
      *dev*)
        conda config --append channels kimlab/label/dev;
        conda config --append channels kimlab;
        conda config --append channels ostrokach/label/dev;
        conda config --append channels ostrokach;
      ;;
      *)
        conda config --append channels kimlab;
        conda config --append channels ostrokach;
      ;;
      esac
    # Clear cache
    - rm -rf /opt/conda/pkgs/*
    # Update conda
    - conda update -n root -yq conda conda-build --no-channel-priority

# === Build ===

.build: &build
  stage: build
  script:
    # Build conda packages
    - cd "${CI_PROJECT_DIR}/.conda"
    - conda build . 
      --no-test
      --python $PYTHON_VERSION
      --cache-dir "${CI_PROJECT_DIR}/conda-cache"
      --output-folder "${CI_PROJECT_DIR}/conda-bld"
  artifacts:
    paths:
      - conda-bld

build-py35:
  <<: [*conda_configure, *build]
  variables:
    <<: [*py35]

build-py36:
  <<: [*conda_configure, *build]
  variables:
    <<: [*py36]

# === Test ===

.test: &test
  stage: test
  script:
    # Restore built packages
    - cp -r $CI_PROJECT_DIR/conda-bld/* /opt/conda/conda-bld/
    - conda index /opt/conda/conda-bld/
    # Run tests
    - cd $CI_PROJECT_DIR/.conda
    - conda build .
      --test
      --python $PYTHON_VERSION 
      --cache-dir "${CI_PROJECT_DIR}/conda-cache"
  coverage: /^TOTAL.* (\d+\%)/
  artifacts:
    paths:
      - environment-py${PYTHON_VERSION/./}.yml

test-py35:
  <<: [*conda_configure, *test]
  dependencies:
    - build-py35
  variables:
    <<: [*py35]

test-py36:
  <<: [*conda_configure, *test]
  dependencies:
    - build-py36
  variables:
    <<: [*py36]

# === Pages ===

.docs: &docs
  stage: test
  script:
    # Restore built packages
    - cp -r $CI_PROJECT_DIR/conda-bld/* /opt/conda/conda-bld/
    - conda index /opt/conda/conda-bld/
    # Install required packages
    - conda install -yq --use-local "python=$PYTHON_VERSION" $CI_PROJECT_NAME
    - conda install -yq nbconvert ipython ipykernel pandoc
    - pip install -q sphinx sphinx_rtd_theme recommonmark nbsphinx
    # Build docs
    - (cd docs && sphinx-apidoc ../kmbio -o api/generated -TeMP)
    - sphinx-build docs public

test-pages:
  <<: [*conda_configure, *docs]
  dependencies:
    - build-py36
  variables:
    <<: [*py36]
  except:
    - master
    - tags

pages:
  <<: [*conda_configure, *docs]
  dependencies:
    - build-py36
  variables:
    <<: [*py36]
  only:
    - master
    - tags
  except:
    - triggers
  artifacts:
    paths:
      - public

# === Deploy ===

.deploy: &deploy
  stage: deploy
  before_script:
    - conda install twine -yq --no-channel-priority
  script:
    # Rename wheels from `-linux_x86_64.whl` to `-manylinux1_x86_64.whl`
    # so that they can be uploaded to PyPI.
    - for i in $CI_PROJECT_DIR/conda-bld/linux-64/*.whl ; do
      echo $i ;
      if [[ $i = *"-linux_x86_64.whl" ]]; then
        mv "${i}" "${i%%-linux_x86_64.whl}-manylinux1_x86_64.whl" ;
      fi ;
      done
    # Development releases go to the Anaconda dev channel
    - if [[ ${PACKAGE_VERSION} = *"dev"* ]] ; then
        anaconda -t $ANACONDA_TOKEN upload $CI_PROJECT_DIR/conda-bld/linux-64/*.tar.bz2 -u ${CI_PROJECT_NAMESPACE} --label dev --force --no-progress ;
       fi
    # Tagged releases go to the Anaconda and PyPI main channels
    - if [[ -n ${CI_COMMIT_TAG} ]] ; then
        anaconda -t $ANACONDA_TOKEN upload $CI_PROJECT_DIR/conda-bld/linux-64/*.tar.bz2 -u ${CI_PROJECT_NAMESPACE} --no-progress ;
        twine upload $CI_PROJECT_DIR/conda-bld/linux-64/*.whl ;
      fi

deploy-py35:
  <<: *deploy
  dependencies:
    - build-py35

deploy-py36:
  <<: *deploy
  dependencies:
    - build-py36
