image: registry.gitlab.com/ostrokach-docker/conda:latest

stages:
  - lint
  - build
  - test
  - deploy

# === Variables ===

variables:
  PACKAGE_VERSION: "2.0.6"

.py35: &py35
  PYTHON_VERSION: "3.5"

.py36: &py36
  PYTHON_VERSION: "3.6"

# === Configurations ===

.configure: &configure
  cache:
    key: ${CI_JOB_NAME}
    paths:
      - .ci/conda_packages/*.tar.bz2
      - .ci/conda_packages/urls.txt
  before_script:
    # Conda environment variables
    - export CONDA_PKGS_DIRS="$CI_PROJECT_DIR/.ci/conda_packages"
    # Make conda cache and bld folders
    - mkdir -p "$CI_PROJECT_DIR/conda-bld" "${CONDA_PKGS_DIRS}"
    # Conda configure
    - conda config --set channel_priority true
    - conda config --append pkgs_dirs "${CONDA_PKGS_DIRS}"
    - conda config --add channels kimlab
    - conda config --add channels conda-forge
    - conda config --add channels defaults
    # - case "${PACKAGE_VERSION}" in
    #   *dev*)
    #     conda config --append channels kimlab/label/dev;
    #     conda config --append channels kimlab;
    #   ;;
    #   *)
    #     conda config --append channels kimlab;
    #   ;;
    #   esac
    # Clear cache
    - rm -rf /opt/conda/pkgs/*
    # Update conda
    - conda update -n root -yq conda conda-build --no-channel-priority

# === Lint ===

lint:
  stage: lint
  <<: [*configure]
  variables:
    <<: [*py36]
  script:
    - cd $(dirname ${CI_CONFIG_PATH})
    - conda install -yq "python=${PYTHON_VERSION}" isort flake8 mypy
    - python -m isort -p ${CI_PROJECT_NAME} -c
    - python -m flake8
    # - black --config pyproject.toml --check .
    # MyPy does not support namespace packages until this issue gets resolved:
    # https://github.com/python/mypy/issues/1645
    # - python -m mypy -p ${CI_PROJECT_NAME}

# === Build ===

.build: &build
  stage: build
  script:
    - cd "${CI_PROJECT_DIR}/.ci/conda"
    - conda build .
      --no-test
      --python $PYTHON_VERSION
      --output-folder "$CI_PROJECT_DIR/conda-bld"
  artifacts:
    paths:
      - conda-bld

build-py35:
  <<: [*configure, *build]
  variables:
    <<: [*py35]

build-py36:
  <<: [*configure, *build]
  variables:
    <<: [*py36]

# === Test ===

.test: &test
  stage: test
  script:
    # Restore built packages
    - cp -r $CI_PROJECT_DIR/conda-bld/* /opt/conda/conda-bld/
    - conda index /opt/conda/conda-bld/
    # Run tests
    - cd ${CI_PROJECT_DIR}/.ci/conda
    - conda build .
      --test
      --python $PYTHON_VERSION
  coverage: /^TOTAL.* (\d+\%)/
  artifacts:
    paths:
      - environment-py${PYTHON_VERSION/./}.yml
      - .ci/conda/.coverage

test-py35:
  <<: [*configure, *test]
  dependencies:
    - build-py35
  variables:
    <<: [*py35]

test-py36:
  <<: [*configure, *test]
  dependencies:
    - build-py36
  variables:
    <<: [*py36]

# === Docs ===

docs:
  stage: test
  <<: [*configure]
  script:
    # Restore built packages
    - cp -r $CI_PROJECT_DIR/conda-bld/* /opt/conda/conda-bld/
    - conda index /opt/conda/conda-bld/
    # Install required packages
    - conda install -yq --use-local "python=$PYTHON_VERSION" $CI_PROJECT_NAME
    - conda install -yq nbconvert ipython ipykernel pandoc
    - pip install -q sphinx sphinx_rtd_theme recommonmark nbsphinx
    # Build docs
    - sphinx-build ${CI_PROJECT_DIR}/docs public
  dependencies:
    - build-py36
  variables:
    <<: [*py36]
  artifacts:
    paths:
      - public
  except:
    - triggers

# === Deploy ===

.deploy: &deploy
  stage: deploy
  before_script:
    - conda install twine -yq --no-channel-priority
  script:
    # Rename wheels from `*-linux_x86_64.whl` to `*-manylinux1_x86_64.whl`
    # so that they can be uploaded to PyPI.
    - for i in $CI_PROJECT_DIR/conda-bld/linux-64/*.whl ; do
      echo $i ;
      if [[ $i = *"-linux_x86_64.whl" ]]; then
        mv "${i}" "${i%%-linux_x86_64.whl}-manylinux1_x86_64.whl" ;
      fi ;
      done
    # Development releases go to the Anaconda dev channel
    - if [[ ${PACKAGE_VERSION} = *"dev"* ]] ; then
        anaconda -t $ANACONDA_TOKEN upload $CI_PROJECT_DIR/conda-bld/linux-64/*.tar.bz2 -u kimlab --label dev --force --no-progress ;
       fi
    # Tagged releases go to the Anaconda and PyPI main channels
    - if [[ -n ${CI_COMMIT_TAG} ]] ; then
        anaconda -t $ANACONDA_TOKEN upload $CI_PROJECT_DIR/conda-bld/linux-64/*.tar.bz2 -u kimlab --no-progress ;
        twine upload $CI_PROJECT_DIR/conda-bld/linux-64/*.whl ;
      fi

deploy-py35:
  <<: *deploy
  dependencies:
    - build-py35

deploy-py36:
  <<: *deploy
  dependencies:
    - build-py36

# === Pages ===

pages:
  stage: deploy
  before_script:
    - sudo yum install -y -q unzip
  script:
    # Create docs folder for the current version
    - mv public "v${PACKAGE_VERSION%.dev}"
    - mkdir public
    - mv "v${PACKAGE_VERSION%.dev}" public/
    # Create docs folder for each tag
    - 'for tag in $(git tag) ; do
      echo ${tag} ;
      curl -L --header "JOB-TOKEN: $CI_JOB_TOKEN"
      "https://gitlab.com/${CI_PROJECT_NAME}/${CI_PROJECT_NAMESPACE}/-/jobs/artifacts/${tag}/download?job=docs"
      -o artifact-${tag}.zip || continue ;
      unzip artifact-${tag}.zip -d public || continue ;
      rm -rf public/${tag} ;
      mv public/public public/${tag} ;
      done'
    # Create index file
    # TODO:
  dependencies:
    - docs
  artifacts:
    paths:
      - public
  only:
    - master
    - tags
  except:
    - triggers
