image: condaforge/linux-anvil:latest

stages:
  - build
  - test
  - deploy

# === Variables ===

variables:
  PACKAGE_VERSION: 2.0.4

.py35: &py35
  PYTHON_VERSION: "3.5"

.py36: &py36
  PYTHON_VERSION: "3.6"

# === Build ===

.conda_configure: &conda_configure
  before_script:
    # Conda configure
    - conda config --set channel_priority true
    - conda config --append channels conda-forge
    - conda config --append channels ostrokach-forge
    - conda config --append channels bioconda
    - case "${PACKAGE_VERSION}" in
      *dev*)
        conda config --append channels kimlab/label/dev;
        conda config --append channels kimlab;
        conda config --append channels ostrokach/label/dev;
        conda config --append channels ostrokach;
      ;;
      *)
        conda config --append channels kimlab;
        conda config --append channels ostrokach;
      ;;
      esac
    # Update conda
    - conda update -n root -yq conda --no-channel-priority
    - conda update -n root -yq conda-build python --no-channel-priority

.build: &build
  stage: build
  script:
    # Build conda packages
    - cd $CI_PROJECT_DIR/.conda
    - conda build --python $PYTHON_VERSION --no-test .
    # Save built packages as artifacts
    - mkdir -p $CI_PROJECT_DIR/conda-bld
    - cp -r /opt/conda/conda-bld/{linux-64,noarch} $CI_PROJECT_DIR/conda-bld
  artifacts:
    paths:
    - conda-bld

build-py35:
  <<: [*conda_configure, *build]
  variables:
    <<: [*py35]

build-py36:
  <<: [*conda_configure, *build]
  variables:
    <<: [*py36]

# === Test ===

.test: &test
  stage: test
  script:
    # Restore built packages
    - cp -r $CI_PROJECT_DIR/conda-bld/* /opt/conda/conda-bld/
    - conda index /opt/conda/conda-bld/
    # Run tests
    - cd $CI_PROJECT_DIR/.conda
    - conda build --python $PYTHON_VERSION --test .
  coverage: /^TOTAL.* (\d+\%)/
  artifacts:
    paths:
      - environment-py${PYTHON_VERSION/./}.yml

test-py35:
  <<: [*conda_configure, *test]
  dependencies:
    - build-py35
  variables:
    <<: [*py35]

test-py36:
  <<: [*conda_configure, *test]
  dependencies:
    - build-py36
  variables:
    <<: [*py36]

# === Pages ===

.docs: &docs
  stage: test
  script:
    # Conda install
    - cp -r $CI_PROJECT_DIR/conda-bld/* /opt/conda/conda-bld/
    - conda index /opt/conda/conda-bld/
    - conda install -y -q --use-local "python=$PYTHON_VERSION" $CI_PROJECT_NAME >/dev/null
    # Build docs
    - conda install -yq nbconvert ipython ipykernel pandoc
    - pip install -q sphinx sphinx_rtd_theme recommonmark nbsphinx
    - (cd docs && sphinx-apidoc ../kmbio -o api/generated -TeMP)
    - sphinx-build docs public

test-pages:
  <<: [*conda_configure, *docs]
  dependencies:
    - build-py36
  variables:
    <<: [*py36]
  except:
    - master
    - tags

pages:
  <<: [*conda_configure, *docs]
  dependencies:
    - build-py36
  variables:
    <<: [*py36]
  only:
    - master
    - tags
  except:
    - triggers
  artifacts:
    paths:
    - public

# === Deploy ===

.deploy: &deploy
  stage: deploy
  script:
    # Conda configure
    - case "${PACKAGE_VERSION}" in
      *dev*)
        anaconda -t $ANACONDA_TOKEN upload $CI_PROJECT_DIR/conda-bld/linux-64/*.tar.bz2 -u ${CI_PROJECT_NAMESPACE} --label dev --force
      ;;
      *)
        anaconda -t $ANACONDA_TOKEN upload $CI_PROJECT_DIR/conda-bld/linux-64/*.tar.bz2 -u ${CI_PROJECT_NAMESPACE}
      ;;
      esac
  only:
    - master
  except:
    - triggers

deploy-py35:
  <<: *deploy
  dependencies:
    - build-py35

deploy-py36:
  <<: *deploy
  dependencies:
    - build-py36
