package:
  name: kmbio
  version: 1.69.3

source:
  path: ../../

build:
  script: $PYTHON setup.py install --single-version-externally-managed --record=record.txt
  number: 0

requirements:
  build:
    - python
    - numpy
    - reportlab
    - mmtf-python
    - cython
    - setuptools
    - wheel
  run:
    - python
    - numpy
    - reportlab
    - biopython
    - mmtf-python
    # Binaries
    - bwa
    - clustalo
    - clustalw
    - emboss
    - mafft
    - muscle
    - paml
    # - phyml
    # - probcons
    - samtools
    # - wise2

test:
  imports:
    - Bio
    - Bio.KDTree
    - Bio.KDTree._CKDTree
    - kmbio.PDB
    - kmbio.PDB.QCPSuperimposer
    - kmbio.PDB.mmtf
    - kmbio.PDB._mmcif_to_dict
    - kmbio.PDB._shlex
    - Bio.SVDSuperimposer
