package:
  name: kmbio
  version: 2.0.13

source:
  path: ../../

build:
  script: python setup.py install --single-version-externally-managed --record=record.txt
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - cython
    - numpy
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - mmtf-python
    - pandas
    - biopython
    - certifi
    - tenacity
    - pyyaml

test:
  source_files:
    - setup.cfg
    - tests
  imports:
    - kmbio
    - kmbio.KDTree
    - kmbio.KDTree._CKDTree
    - kmbio.PDB
    - kmbio.PDB.core
    - kmbio.PDB.io
    - kmbio.PDB.parsers
    - kmbio.PDB.parsers._shlex
    - kmbio.PDB.parsers._mmcif_to_dict
    - kmbio.PDB.tools
    - kmbio.PDB.tools.QCPSuperimposer
    - kmbio.PDB.tools.QCPSuperimposer.qcprotmodule
    - Bio.SVDSuperimposer
  requires:
    - flake8
    - pytest
    - pytest-cov
    - pytest-benchmark
    - hypothesis
    # Binaries
    - hh-suite

about:
  home: https://gitlab.com/kimlab/kmbio
  license: BioPython License
  summary: "Fork of `biopython.PDB` with special powers."
