package:
  name: kmbio
  version: 2.0.6

source:
  path: ../../

build:
  script: $PYTHON setup.py install --single-version-externally-managed --record=record.txt
  number: 0

requirements:
  host:
    - setuptools
    - wheel
    - numpy
    - cython
    - python
    - mmtf-python
  build:
    - {{ compiler('c') }}
  run:
    - python
    - numpy
    - mmtf-python
    - pandas
    - biopython
    - retrying
    - pyyaml

test:
  imports:
    - Bio
    - Bio.KDTree
    - Bio.KDTree._CKDTree
    - kmbio.PDB
    - kmbio.PDB.core
    - kmbio.PDB.io
    - kmbio.PDB.parsers
    - kmbio.PDB.parsers._shlex
    - kmbio.PDB.parsers._mmcif_to_dict
    - kmbio.PDB.tools
    - kmbio.PDB.tools.QCPSuperimposer
    - Bio.SVDSuperimposer
  requires:
    - flake8
    - pytest
    - pytest-cov
    - hypothesis

outputs:
  - name: kmbio
    type: conda
  - type: wheel

about:
  home: https://gitlab.com/kimlab/kmbio
  license: BioPython License
  summary: "Fork of `biopython.PDB` with special powers."
